spring:
  application:
    name: gateway
  profiles:
    #active: prod
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  main:
    allow-bean-definition-overriding: true

